server:
  port: 8889

spring:
  application:
    name: springboot-log4j2
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:8889
info:
  name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS