server:
  port: 8081

spring:
  profiles:
    active: dev
  application:
    name: springboot-actuator
  boot:
    admin:
      client:
        url: http://localhost:8888/springboot-admin
        username: admin
        password: admin@root
        instance:
          service-base-url: http://localhost:8081
          metadata:
            tags:
              environment: ${spring.profiles.active}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    name: ./logs/springboot-actuator.log