server:
  port: 8081

spring:
  application:
    name: springboot-actuator
  boot:
    admin:
      client:
        url: http://localhost:8088
        username: "admin"
        password: "admin"
        instance:
          service-base-url: http://localhost:8081
info:
  name: actuator

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: /log/actuator.log