server:
  port: 8081

spring:
  application:
    name: springboot-actuator
  boot:
    admin:
      client:
        url: http://localhost:8888
        username: admin
        password: admin
        instance:
          service-base-url: http://localhost:8081
info:
  name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file:
    path: logs/actuator.log