spring:
  redis:
    database: 11
    host: 47.112.108.222
    password: qazwsxedcrfvtgbyhnujmik
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 5

logging:
  level:
    com.mm: debug
