spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT+8
    property-naming-strategy: SNAKE_CASE

logging:
  level:
    com.mm: debug

springdoc:
  paths-to-match: /user
#  swagger-ui:
#    version: 1.0.0
