server:
  port: 8888
  servlet:
    context-path: /springboot-admin

spring:
  application:
    name: springboot-admin
  security:
    user:
      name: admin
      password: admin@root
# 邮件通知配置
#  mail:
#    host: smtp.mxhichina.com
#    username: xxx@xxx.com
#    password: xxx
#  boot:
#    admin:
#      notify:
#        mail:
#          from: xxx@xxx.com   # 必填
#          to: xxx@qq.com

dingtalk:
  webhook: https://oapi.dingtalk.com/robot/send?access_token=d3547be1e674ddfb340e9ba92656af30410a4f560227aa8ed49f24d060de3644
  secret: SEC04510bd2627bb3e8bc54799fb92cd86d53b556d98e982bf018b7e7301d9edceb