server:
  port: 8888
  servlet:
    context-path: /springboot-admin

spring:
  application:
    name: springboot-admin
  security:
    user:
      name: admin
      password: admin@root
# 邮件通知配置
#  mail:
#    host: smtp.mxhichina.com
#    username: xxx@xxx.com
#    password: xxx
#  boot:
#    admin:
#      notify:
#        mail:
#          from: xxx@xxx.com   # 必填
#          to: xxx@qq.com