server:
  port: 8088

spring:
  application:
    name: springboot-admin

info:
  name: admin

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: /log/admin.log
